const TURNSTILE_ORIGIN = 'https://challenges.cloudflare.com';

export function createCspNonce() {
  // A UUID is generated by the Worker crypto runtime, then encoded as a CSP-safe
  // base64 value. It is deliberately request-scoped and never persisted.
  return btoa(crypto.randomUUID());
}

export function createContentSecurityPolicy(nonce: string | null, development = false) {
  if (!development && !nonce) {
    throw new Error('A production Content Security Policy requires a script nonce.');
  }

  const scriptSources = [
    "'self'",
    ...(nonce ? [`'nonce-${nonce}'`] : []),
    TURNSTILE_ORIGIN,
    ...(development ? ["'unsafe-inline'", "'unsafe-eval'"] : [])
  ].join(' ');
  const connectSources = [
    "'self'",
    TURNSTILE_ORIGIN,
    ...(development ? ['ws:', 'wss:'] : [])
  ].join(' ');

  return [
    "default-src 'self'",
    `script-src ${scriptSources}`,
    "script-src-attr 'none'",
    `frame-src ${TURNSTILE_ORIGIN}`,
    `connect-src ${connectSources}`,
    "img-src 'self' data:",
    "style-src 'self' 'unsafe-inline'",
    "font-src 'self'",
    "object-src 'none'",
    "base-uri 'self'",
    "frame-ancestors 'none'",
    "form-action 'self'"
  ].join('; ');
}
