import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { LanguageSwitch } from '@/components/site';
import { getArticle, getArticles, readArticle, renderMarkdown } from '@/lib/content';
import { categories, isLocale, ui } from '@/lib/i18n';
import { LOCALES } from '@/lib/types';
export function generateStaticParams(){return LOCALES.flatMap(lang=>getArticles().map(a=>({lang,slug:a.slug})));}
export async function generateMetadata({params}:{params:Promise<{lang:string;slug:string}>}):Promise<Metadata>{const {lang,slug}=await params;const article=getArticle(slug);if(!isLocale(lang)||!article)return{};const copy=article.translations[lang];return{title:copy.title,description:copy.description,alternates:{canonical:`/${lang}/articles/${slug}`,languages:{'zh-Hant':`/zh-Hant/articles/${slug}`,'zh-Hans':`/zh-Hans/articles/${slug}`,en:`/en/articles/${slug}`,'x-default':`/zh-Hant/articles/${slug}`}}};}
export default async function ArticlePage({params}:{params:Promise<{lang:string;slug:string}>}){const {lang,slug}=await params;const article=getArticle(slug);if(!isLocale(lang)||!article)notFound();const copy=article.translations[lang];const category=categories[article.categoryId][lang];const body=readArticle(article,lang);return <div className="article-shell"><header className="article-header"><Link className="category-label" href={`/${lang}/categories/${article.categoryId}`}>{category.name}</Link><h1>{copy.title}</h1><p className="article-dek">{copy.description}</p><div className="article-meta"><span>{article.type.replace('-',' ')}</span><span>{ui[lang].updated as string} {article.updatedAt}</span><span>v1.0</span></div><LanguageSwitch locale={lang} slug={slug}/></header><article className="prose">{renderMarkdown(body)}</article><aside className="downloads"><div><p className="eyebrow">{ui[lang].download as string}</p><h2>{copy.title}</h2><p>{lang==='en'?'Use the editable worksheet or print the one-page PDF.':'可下載編輯版 worksheet，或列印一頁 PDF。'}</p></div><div className="download-actions"><a className="button primary" download href={`/downloads/${article.id}/v1/${lang}.pdf`}>PDF</a><a className="button secondary" download href={`/downloads/${article.id}/v1/${lang}.md`}>Markdown</a></div></aside><section className="sources"><h2>{ui[lang].source as string}</h2><p>{article.reviewedAt} · next review {article.reviewBy}</p><ul>{article.sourceUrls.map(url=><li key={url}><a href={url} rel="noreferrer">{new URL(url).hostname}</a></li>)}</ul></section></div>}
